stages:
  visual_train:
    cmd: >
      python -m src.visual.models.train
      --data-yaml store/data/raw/visual_data/yolo_nano/mmcows_binary.yaml
      --model yolov8n.pt
      --epochs 50
      --imgsz 640
      --batch 16
      --device cpu
      --workers 4
      --project store/models/visual
      --name cow_detection_v8n
    deps:
    - src/visual/models/train.py
    - store/data/raw/visual_data/yolo_nano/mmcows_binary.yaml
    - store/data/raw/visual_data/yolo_nano/train.txt
    - store/data/raw/visual_data/yolo_nano/val.txt
    outs:
    - store/models/visual
