experiment_name: "Feature_Selection"
modality: "immu"

data:
  sensor_data_dir: "/home/haythem/pfa-mmcows/store/data/raw/sensor_data"
  pre_loader: "immu_pre_data_loader"
  date: "0725"
  fold_config:
    train: [1, 2] # Example IDs for testing
    val: [3]
    test: [4]

features:
  window_size: 100
  overlap: 0.5
  sample_rate: 10.0

selection:
  variance_threshold: 1e-10
  pearson_threshold: 0.9
  rf_n_estimators: 200

evaluation:
  k_values: [20, 50, 100, 'all']

mlflow:
  enabled: true
  tracking_uri: "sqlite:///mlflow.db"

output_dir: "results"