sensor_data_dir: C:\Users\Iheb\Documents\RT4 2025-2026\Semestre 2\PFA\dataset\sensor_data
visual_data_dir: C:\Users\Iheb\Documents\RT4 2025-2026\Semestre 2\PFA\dataset\visual_data
split_config_dir: C:\Users\Iheb\Documents\RT4 2025-2026\Semestre 2\PFA\Main Workplace\mmcows_internal\configs



