data:
  sensor_data_dir: "store/data/raw/sensor_data"  # Update with your actual path
  fold_config: "configs/config_s1.json" # Or whatever your fold config is
  date: "0725"
  pre_loader: "immu_pre_data_loader"      # Update with your actual loader function name

modality: "immu"

features:
  window_size: 100
  overlap: 0.5
  sample_rate: 10.0

selection:
  pearson_threshold: 0.9
  rf_n_estimators: 200

evaluation:
  k_values: [20, 50, 100, 'all']

mlflow:
  enabled: true
  experiment_name: "Sensor_Feature_Selection"
  tracking_uri: "http://127.0.0.1:5000"