"""Prepare YOLO binary artifacts from dataset_index.pkl.

Optional behavior can remap all label class ids to 0 in place.
It always writes train/val/test text files and a dataset YAML.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert indexed visual data to YOLO binary format.")
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("store/data/raw/visual_data"),
        help="Root directory of visual dataset.",
    )
    parser.add_argument(
        "--index-file",
        type=Path,
        default=None,
        help="Path to dataset_index.pkl. Defaults to <dataset-root>/dataset_index.pkl.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output dir for train/val/test txt and mmcows_binary.yaml. Defaults to <dataset-root>/yolo_nano.",
    )
    parser.add_argument(
        "--remap-labels-in-place",
        action="store_true",
        help="If set, remap all class IDs in label files to 0.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing files.",
    )
    return parser.parse_args()


def remap_label_file(lbl_path: Path, dry_run: bool = False) -> tuple[bool, int]:
    text = lbl_path.read_text(encoding="utf-8").strip()
    if not text:
        return True, 0

    lines = text.splitlines()
    new_lines: list[str] = []
    remapped = 0

    for line in lines:
        parts = line.strip().split()
        if len(parts) < 5:
            continue
        if parts[0] != "0":
            parts[0] = "0"
            remapped += 1
        new_lines.append(" ".join(parts))

    if remapped == 0:
        return True, 0

    if not dry_run:
        lbl_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    return False, remapped


def write_split_txts(df: pd.DataFrame, out_dir: Path, dry_run: bool) -> None:
    for split in ["train", "val", "test"]:
        subset = df[df["split"] == split]
        lines = [f"{str(path)}\n" for path in subset["img_path"]]
        output_path = out_dir / f"{split}.txt"
        if dry_run:
            print(f"[DRY] Would write {len(lines)} lines to {output_path}")
        else:
            output_path.write_text("".join(lines), encoding="utf-8")
            print(f"[OK] Wrote {len(lines)} lines to {output_path}")


def write_yaml(out_dir: Path, dataset_root: Path, df: pd.DataFrame, dry_run: bool) -> None:
    yaml_path = out_dir / "mmcows_binary.yaml"
    content = "\n".join(
        [
            "# Auto-generated by a2_yolo_binary.py",
            f"path: {dataset_root.resolve()}",
            f"train: {(out_dir / 'train.txt').resolve()}",
            f"val: {(out_dir / 'val.txt').resolve()}",
            f"test: {(out_dir / 'test.txt').resolve()}",
            "",
            "nc: 1",
            "names: ['cow']",
            "",
            f"# total: {len(df)}",
            f"# train: {len(df[df['split'] == 'train'])}",
            f"# val: {len(df[df['split'] == 'val'])}",
            f"# test: {len(df[df['split'] == 'test'])}",
        ]
    )

    if dry_run:
        print(f"[DRY] Would write dataset yaml to {yaml_path}")
    else:
        yaml_path.write_text(content + "\n", encoding="utf-8")
        print(f"[OK] Wrote dataset yaml to {yaml_path}")


def main() -> None:
    args = parse_args()
    dataset_root = args.dataset_root.resolve()
    index_file = args.index_file.resolve() if args.index_file else dataset_root / "dataset_index.pkl"
    output_dir = args.output_dir.resolve() if args.output_dir else dataset_root / "yolo_nano"

    if not index_file.exists():
        raise FileNotFoundError(f"Index file not found: {index_file}")

    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_pickle(index_file)
    print(f"[OK] Loaded {len(df)} samples from {index_file}")

    if args.remap_labels_in_place:
        skipped = 0
        changed_files = 0
        changed_lines = 0
        for lbl in df["lbl_path"]:
            was_skipped, count = remap_label_file(Path(lbl), dry_run=args.dry_run)
            if was_skipped:
                skipped += 1
            else:
                changed_files += 1
                changed_lines += count
        print(
            "[OK] Label remap summary: "
            f"files_changed={changed_files}, lines_changed={changed_lines}, skipped={skipped}"
        )

    write_split_txts(df, out_dir=output_dir, dry_run=args.dry_run)
    write_yaml(out_dir=output_dir, dataset_root=dataset_root, df=df, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
"""
A2 — Convert to YOLO binary format
====================================
Reads dataset_index.pkl produced by A1.
For every label file, remaps ALL class IDs → 0  (binary: cow vs background).
Rewrites label files IN-PLACE (no copies — storage-safe).
Writes train.txt / val.txt / test.txt and mmcows_binary.yaml
under  <DATASET_ROOT>/yolo_nano/.

Steps
-----
1. Load dataset_index.pkl
2. For each row, read the .txt label line-by-line
   - YOLO line format: <class_id> <cx> <cy> <w> <h>
   - Replace class_id with 0, keep bbox unchanged
3. Write back to the same lbl_path (in-place, no copy)
4. Write yolo_nano/train.txt, val.txt, test.txt
   (one absolute image path per line)
5. Write yolo_nano/mmcows_binary.yaml

Safety
------
- A dry-run mode (DRY_RUN = True) prints diffs without writing anything.
- Labels that are already all-zero are skipped (idempotent).
- Empty label files (background tiles) are left untouched.
"""

from pathlib import Path
import pandas as pd

# ── Configuration ─────────────────────────────────────────────────────────────
DATASET_ROOT = Path(r"C:\Users\DELL\Desktop\test\mmcows\data\raw\visual_data")          # ← same root as A1
INDEX_FILE   = DATASET_ROOT / "dataset_index.pkl"
OUT_DIR      = DATASET_ROOT / "yolo_nano"
DRY_RUN      = False          # set True to preview without writing anything
# ─────────────────────────────────────────────────────────────────────────────


# def remap_label_file(lbl_path: Path, dry_run: bool = False) -> dict:
#     """
#     Read a YOLO .txt label, remap all class IDs → 0, write back in-place.
#     Returns a stats dict: {skipped, remapped, lines}.
#     """
#     text = lbl_path.read_text().strip()

#     if not text:                       # background tile — nothing to remap
#         return {"skipped": True, "remapped": 0, "lines": 0}

#     lines     = text.splitlines()
#     new_lines = []
#     remapped  = 0

#     for line in lines:
#         parts = line.strip().split()
#         if not parts:
#             continue
#         cls_id = int(parts[0])
#         if cls_id != 0:
#             parts[0] = "0"
#             remapped += 1
#         new_lines.append(" ".join(parts))

#     already_binary = (remapped == 0)
#     if already_binary:
#         return {"skipped": True, "remapped": 0, "lines": len(new_lines)}

#     if not dry_run:
#         lbl_path.write_text("\n".join(new_lines) + "\n")

#     return {"skipped": False, "remapped": remapped, "lines": len(new_lines)}


def write_split_txts(df: pd.DataFrame, out_dir: Path, dry_run: bool) -> None:
    for split in ["train", "val", "test"]:
        subset = df[df["split"] == split]
        lines  = [str(p) + "\n" for p in subset["img_path"]]
        path   = out_dir / f"{split}.txt"
        if dry_run:
            print(f"  [DRY] Would write {len(lines)} lines → {path}" )
        else:
            path.write_text("".join(lines))
            print(f"  Wrote {len(lines):>5} lines → {path}")


def write_yaml(out_dir: Path, df: pd.DataFrame, dry_run: bool) -> None:
    yaml_path = out_dir / "mmcows_binary.yaml"
    content = f"""\
# mmcows_binary.yaml — generated by A2
# Binary detection: all cow IDs collapsed to class 0

path  : {DATASET_ROOT.resolve()}
train : {(out_dir / 'train.txt').resolve()}
val   : {(out_dir / 'val.txt').resolve()}
test  : {(out_dir / 'test.txt').resolve()}

nc     : 1
names  : ['cow']

# Dataset stats
# Total samples : {len(df)}
# Train         : {len(df[df['split'] == 'train'])}
# Val           : {len(df[df['split'] == 'val'])}
# Test          : {len(df[df['split'] == 'test'])}
# Cameras       : {sorted(df['cam'].unique().tolist())}
"""
    if dry_run:
        print(f"\n[DRY] Would write yaml → {yaml_path}")
        print(content)
    else:
        yaml_path.write_text(content)
        print(f"  Wrote yaml  → {yaml_path}")


def main() -> None:
    # ── Load index ────────────────────────────────────────────────────────
    if not INDEX_FILE.exists():
        print(f"[ERROR] Index not found: {INDEX_FILE}")
        print("        Run a1_build_index.py first.")
        return

    df = pd.read_pickle(INDEX_FILE)
    print(f"Loaded index: {len(df)} samples across {df['cam'].nunique()} cameras.\n")

    if DRY_RUN:
        print("*** DRY RUN — no files will be modified ***\n")

    # ── Remap labels in-place ─────────────────────────────────────────────
    # print("Remapping class IDs → 0 in label files ...")
    # total_remapped = 0
    # total_skipped  = 0
    # total_files    = 0

    # for _, row in df.iterrows():
    #     lbl_path = Path(row["lbl_path"])
    #     stats    = remap_label_file(lbl_path, dry_run=DRY_RUN)
    #     total_files += 1
    #     if stats["skipped"]:
    #         total_skipped += 1
    #     else:
    #         total_remapped += 1

    # print(f"  Files processed : {total_files}")
    # print(f"  Already binary  : {total_skipped}  (skipped, no write needed)")
    # print(f"  Remapped        : {total_remapped}  (written in-place)\n")

    # ── Write split txts ──────────────────────────────────────────────────
    print("Writing split .txt files ...")
    if not DRY_RUN:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
    write_split_txts(df, OUT_DIR, dry_run=DRY_RUN)

    # ── Write yaml ────────────────────────────────────────────────────────
    print("\nWriting mmcows_binary.yaml ...")
    write_yaml(OUT_DIR, df, dry_run=DRY_RUN)

    # ── Verify label sample ───────────────────────────────────────────────
    if not DRY_RUN:
        print("\nSpot-check — first 3 label files after remap:")
        for _, row in df.head(3).iterrows():
            lbl_path = Path(row["lbl_path"])
            content  = lbl_path.read_text().strip()
            classes  = {int(l.split()[0]) for l in content.splitlines() if l.strip()}
            print(f"  {row['sample_id']}: classes={classes}  ({'OK' if classes <= {0} else 'WARN — non-zero class found!'})")

    print("\nA2 complete.")
    if not DRY_RUN:
        print(f"  Split files + yaml → {OUT_DIR}/")


if __name__ == "__main__":
    main()
