"""Prepare YOLO binary artifacts from dataset_index.pkl.

Optional behavior can remap all label class ids to 0 in place.
It always writes train/val/test text files and a dataset YAML.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert indexed visual data to YOLO binary format.")
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("store/data/raw/visual_data"),
        help="Root directory of visual dataset.",
    )
    parser.add_argument(
        "--index-file",
        type=Path,
        default=None,
        help="Path to dataset_index.pkl. Defaults to <dataset-root>/dataset_index.pkl.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output dir for train/val/test txt and mmcows_binary.yaml. Defaults to <dataset-root>/yolo_nano.",
    )
    parser.add_argument(
        "--remap-labels-in-place",
        action="store_true",
        help="If set, remap all class IDs in label files to 0.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing files.",
    )
    return parser.parse_args()


def remap_label_file(lbl_path: Path, dry_run: bool = False) -> tuple[bool, int]:
    text = lbl_path.read_text(encoding="utf-8").strip()
    if not text:
        return True, 0

    lines = text.splitlines()
    new_lines: list[str] = []
    remapped = 0

    for line in lines:
        parts = line.strip().split()
        if len(parts) < 5:
            continue
        if parts[0] != "0":
            parts[0] = "0"
            remapped += 1
        new_lines.append(" ".join(parts))

    if remapped == 0:
        return True, 0

    if not dry_run:
        lbl_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    return False, remapped


def write_split_txts(df: pd.DataFrame, out_dir: Path, dry_run: bool) -> None:
    for split in ["train", "val", "test"]:
        subset = df[df["split"] == split]
        lines = [f"{str(path)}\n" for path in subset["img_path"]]
        output_path = out_dir / f"{split}.txt"
        if dry_run:
            print(f"[DRY] Would write {len(lines)} lines to {output_path}")
        else:
            output_path.write_text("".join(lines), encoding="utf-8")
            print(f"[OK] Wrote {len(lines)} lines to {output_path}")


def ensure_yolo_label_layout(df: pd.DataFrame, dataset_root: Path, dry_run: bool) -> None:
    images_root = dataset_root / "images"
    linked = 0
    copied = 0
    missing = 0

    for row in df.itertuples(index=False):
        img_path = Path(row.img_path)
        src_lbl = Path(row.lbl_path)

        try:
            rel_img = img_path.relative_to(images_root)
        except ValueError:
            continue

        dst_lbl = (dataset_root / "labels" / rel_img).with_suffix(".txt")
        if dst_lbl.exists():
            continue

        if dry_run:
            continue

        dst_lbl.parent.mkdir(parents=True, exist_ok=True)
        if not src_lbl.exists():
            dst_lbl.write_text("", encoding="utf-8")
            missing += 1
            continue

        try:
            dst_lbl.symlink_to(src_lbl)
            linked += 1
        except OSError:
            shutil.copy2(src_lbl, dst_lbl)
            copied += 1

    if dry_run:
        print("[DRY] Would ensure YOLO label layout under labels/<date>/<cam>/")
    else:
        print(
            "[OK] Label layout ready: "
            f"linked={linked}, copied={copied}, empty_created={missing}"
        )


def write_yaml(out_dir: Path, dataset_root: Path, df: pd.DataFrame, dry_run: bool) -> None:
    yaml_path = out_dir / "mmcows_binary.yaml"
    content = "\n".join(
        [
            "# Auto-generated by a2_yolo_binary.py",
            f"path: {dataset_root.resolve()}",
            f"train: {(out_dir / 'train.txt').resolve()}",
            f"val: {(out_dir / 'val.txt').resolve()}",
            f"test: {(out_dir / 'test.txt').resolve()}",
            "",
            "nc: 1",
            "names: ['cow']",
            "",
            f"# total: {len(df)}",
            f"# train: {len(df[df['split'] == 'train'])}",
            f"# val: {len(df[df['split'] == 'val'])}",
            f"# test: {len(df[df['split'] == 'test'])}",
        ]
    )

    if dry_run:
        print(f"[DRY] Would write dataset yaml to {yaml_path}")
    else:
        yaml_path.write_text(content + "\n", encoding="utf-8")
        print(f"[OK] Wrote dataset yaml to {yaml_path}")


def main() -> None:
    args = parse_args()
    dataset_root = args.dataset_root.resolve()
    index_file = args.index_file.resolve() if args.index_file else dataset_root / "dataset_index.pkl"
    output_dir = args.output_dir.resolve() if args.output_dir else dataset_root / "yolo_nano"

    if not index_file.exists():
        raise FileNotFoundError(f"Index file not found: {index_file}")

    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_pickle(index_file)
    print(f"[OK] Loaded {len(df)} samples from {index_file}")

    ensure_yolo_label_layout(df, dataset_root=dataset_root, dry_run=args.dry_run)

    if args.remap_labels_in_place:
        skipped = 0
        changed_files = 0
        changed_lines = 0
        for lbl in df["lbl_path"]:
            was_skipped, count = remap_label_file(Path(lbl), dry_run=args.dry_run)
            if was_skipped:
                skipped += 1
            else:
                changed_files += 1
                changed_lines += count
        print(
            "[OK] Label remap summary: "
            f"files_changed={changed_files}, lines_changed={changed_lines}, skipped={skipped}"
        )

    write_split_txts(df, out_dir=output_dir, dry_run=args.dry_run)
    write_yaml(out_dir=output_dir, dataset_root=dataset_root, df=df, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
